title: Your awesome title
email: your-email@example.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: ""
twitter_username: TopdocStyle
github_username:  topdoc
permalink: pretty

sass:
  sass_dir: _sass

markdown: kramdown
plugins:
  - jekyll-feed
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - js/src/
  - .cache/
